export default [
  {
    path:'/home',
    component:()=>import("@/pages/Home"),
    meta:{
      show:true,
    },
  },
  {
    name:'trade',
    path:'/trade',
    component:()=>import("@/pages/Trade"),
    meta:{
      show:true,
    },
    beforeEnter:(to,from,next)=>{
      if(from.path.indexOf('/shopcart')!= -1) next()
      else next(false)
    },
  },
  {
    name:'pay',
    path:'/pay',
    component:()=>import("@/pages/Pay"),
    meta:{
      show:true,
    },
    beforeEnter:(to,from,next)=>{
      if(from.path.indexOf('/trade')!= -1) next()
      else next(false)
    },
  },
  {
    name:'paysuccess',
    path:'/paysuccess',
    component:()=>import("@/pages/PaySuccess"),
    meta:{
      show:true,
    },
  },
  {
    path:'/center',
    component:()=>import("@/pages/Center"),
    meta:{
      show:true,
    },
    children:[
      {
        path:'myorder',
        component:()=>import("@/pages/Center/MyOrder"),
      },
      {
        path:'grouporder',
        component:()=>import("@/pages/Center/GroupOrder"),
      },
      {
        path:'',
        redirect:'myorder',
      },
    ],
  },
  {
    path:'/detail/:skuId',
    component:()=>import("@/pages/Detail"),
    meta:{
      show:true,
    },
  },
  {
    path:'/login',
    component:()=>import("@/pages/Login"),
    meta:{
      show:false,
    },
  },
  {
    path:'/register',
    component:()=>import("@/pages/Register"),
    meta:{
      show:false,
    },
  },
  {
    name:'addcartsuccess',
    path:'/addcartsuccess',
    component:()=>import("@/pages/AddCartSuccess"),
    meta:{
      show:true,
    },
  },
  {
    name:'shopcart',
    path:'/shopcart',
    component:()=>import("@/pages/ShopCart"),
    meta:{
      show:true,
    },
  },
  {
    name:'search',
    path:'/search/:keyword?',
    component:()=>import("@/pages/Search"),

    meta:{
      show:true,
    },
    //写法一：布尔值，不能传递额外参数到目标的$attr
    //props:true,
    //写法二：对象形式，可以传递额外参数（a，b）到目标的$attr
    //props: {a: 101, b: 202},
    //写法三：函数形式，可以传递额外参数（ljh）到目标的$attr
    //props:$route=>({keyword:$route.params.keyword,k:$route.query.k,ljh:'23'})
    //综上：路由可以传递props参数，并且函数形式的写法最强大。
    props:$route=>({keyword:$route.params.keyword}),
  },
  //重定向
  {
    path:'/',
    redirect:'/home',
  },
]